Added str method to  models
vitaliisili/petoshield-rest pull request #22
Opened 2023-10-26 14:03 UTC by JulienSchoener

2023-10-26 14:06 UTC, vitaliisili commented on petoshield_api/apps/pet/models.py
> +        return f"{self.name} ({self.species})"
Return only the name of the pet

2023-10-26 14:07 UTC, vitaliisili requested changes
Add also __str__ for policy app models like serviceProvider

2023-10-26 14:30 UTC, JulienSchoener reviewed
check

2023-10-26 14:30 UTC, JulienSchoener commented on petoshield_api/apps/pet/models.py
> +        return f"{self.name} ({self.species})"
updated

2023-10-26 14:37 UTC, vitaliisili commented on petoshield_api/apps/policy/models.py
> +        return self.invoice_date
Here should be invoice amount

2023-10-26 14:38 UTC, vitaliisili requested changes
In policy IncomingInvoice should return invoice anount instead of invoice date

2023-10-27 07:57 UTC, JulienSchoener commented on petoshield_api/apps/policy/models.py
> +        return self.invoice_date
applied changes

2023-10-27 07:58 UTC, vitaliisili approved these changes

2023-10-27 07:58 UTC, merged